project_id = "ukuqflaakynzzikuszjl"

[functions.vapi-chat]
verify_jwt = false

[functions.demo-chat]
verify_jwt = false

[functions.eve-chat]
verify_jwt = false

[functions.elevenlabs-conversation-token]
verify_jwt = false
