project_id = "ccjnxselfgdoeyyuziwt"

[functions.demo-chat]
verify_jwt = false

[functions.eve-chat]
verify_jwt = false

[functions.elevenlabs-conversation-token]
verify_jwt = false

[functions.save-lead]
verify_jwt = false

[functions.calcom-get-slots]
verify_jwt = false

[functions.calcom-create-booking]
verify_jwt = false

[functions.calcom-get-bookings]
verify_jwt = false

[functions.calcom-get-booking]
verify_jwt = false

[functions.calcom-cancel-booking]
verify_jwt = false

[functions.vapi-chat]
verify_jwt = false

[functions.submit-contact-form]
verify_jwt = false

[functions.send-email-contact]
verify_jwt = false
